# Generated by Django 4.2 on 2023-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notify_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
