# Generated by Django 4.2 on 2023-06-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='sender',
        ),
    ]
