# Generated by Django 4.2 on 2023-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_repo_date_alter_repo_repo_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportitemnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_item', models.TextField()),
                ('reported_item_n', models.IntegerField(default=0)),
                ('reported_item_type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='repo',
            name='repo_n',
        ),
    ]
