# Generated by Django 4.2 on 2023-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_person_type_wanted_p_lost_p_found_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted_p',
            name='condition',
            field=models.CharField(choices=[('armed', 'Armed'), ('not_armed', 'Not Armed')], default='not_armed'),
        ),
    ]
