# Generated by Django 4.2 on 2023-05-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_wanted_p_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='found_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.TextField()),
                ('detail', models.TextField()),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lost_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.TextField()),
                ('detail', models.TextField()),
                ('adress', models.CharField(max_length=100)),
                ('i_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.item_type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matched_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('correct', 'Armed'), ('not_correct', 'Not Armed')], default='not_correct')),
                ('found_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.found_p')),
                ('lost_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.lost_p')),
            ],
        ),
        migrations.CreateModel(
            name='matched_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('correct', 'Correct match'), ('not_correct', 'Not Correct Match')], default='not_correct')),
                ('found_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.found_i')),
                ('lost_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.lost_i')),
            ],
        ),
        migrations.AddField(
            model_name='found_i',
            name='i_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.item_type'),
        ),
        migrations.AddField(
            model_name='found_i',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
