# Generated by Django 4.2 on 2023-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_account_city_account_region_found_i_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(choices=[('BD', 'Bahrdar'), ('AD', 'Adama'), ('AA', 'Addis Ababa'), ('JJ', 'Jigjiga')], default='Addis Ababa'),
        ),
    ]
