# Generated by Django 4.2 on 2023-05-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0010_account_is_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matched_i',
            name='city',
        ),
        migrations.RemoveField(
            model_name='matched_i',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='matched_i',
            name='region',
        ),
        migrations.RemoveField(
            model_name='matched_p',
            name='city',
        ),
        migrations.RemoveField(
            model_name='matched_p',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='matched_p',
            name='region',
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.user_type'),
        ),
        migrations.AlterField(
            model_name='found_i',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='found_i',
            name='region',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='found_p',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='found_p',
            name='region',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lost_i',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lost_i',
            name='region',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lost_p',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lost_p',
            name='region',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matched_i',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='matched_p',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wanted_p',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wanted_p',
            name='condition',
            field=models.CharField(choices=[('armed', 'Armed'), ('not_armed', 'Not Armed')], default='not_armed', max_length=100),
        ),
        migrations.AlterField(
            model_name='wanted_p',
            name='region',
            field=models.TextField(),
        ),
    ]
