# Generated by Django 4.2 on 2023-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0012_found_i_lost_date_found_i_update_date_found_p_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
