# Generated by Django 4.2 on 2023-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0014_remove_matched_p_found_id_remove_matched_p_lost_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_p',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='found_p',
            old_name='first_n',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='found_p',
            old_name='last_n',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='lost_p',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='lost_p',
            old_name='first_n',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lost_p',
            old_name='last_n',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='found_i',
            name='post_type',
            field=models.CharField(blank=True, default='found-item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='found_p',
            name='post_type',
            field=models.CharField(blank=True, default='found-person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lost_i',
            name='post_type',
            field=models.CharField(blank=True, default='lost item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lost_p',
            name='post_type',
            field=models.CharField(blank=True, default='lost person', max_length=100, null=True),
        ),
    ]
