# Generated by Django 4.2 on 2023-06-22 21:15

from django.db import migrations, models
import thread.models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0015_rename_adress_found_p_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost_p',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.upload_to),
        ),
    ]
