# Generated by Django 4.2 on 2023-06-22 21:50

from django.db import migrations, models
import thread.models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0016_lost_p_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.uploadaccount_to),
        ),
        migrations.AddField(
            model_name='found_i',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.uploadfoundi_to),
        ),
        migrations.AddField(
            model_name='found_p',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.uploadfoundp_to),
        ),
        migrations.AddField(
            model_name='lost_i',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.uploadlosti_to),
        ),
        migrations.AddField(
            model_name='wanted_p',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=thread.models.uploadwantedp_to),
        ),
    ]
