# Generated by Django 4.2 on 2023-06-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_detail', models.TextField(blank=True, default='about', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='address', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='phone', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='email', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, default='facebook', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='twitter', max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, default='instagram', max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, default='youtube', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_detail', models.TextField(blank=True, default='help', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_detail', models.TextField(blank=True, default='privacy', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, default='region', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_detail', models.TextField(blank=True, default='terms', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='question', null=True)),
                ('answer', models.TextField(blank=True, default='answer', null=True)),
                ('asker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='city', max_length=100, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informations.region')),
            ],
        ),
    ]
