# Generated by Django 4.2 on 2023-06-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0015_rename_adress_found_p_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notif_reciever_matcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matched_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, default='accurate', null=True)),
                ('found_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.found_p')),
                ('lost_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.lost_p')),
            ],
        ),
        migrations.CreateModel(
            name='matched_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(blank=True, default='accurate', null=True)),
                ('found_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.found_i')),
                ('lost_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thread.lost_i')),
            ],
        ),
    ]
